using CsvCommonLib;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SyncFileToDbEFSimple
{
    public class EmployeeAndSsnContext : DbContext
    {
        public EmployeeAndSsnContext(string connectionString)
            : base(connectionString)
        {
            //disable initializer
            // Don't want EF to check for migrations
            Database.SetInitializer<EmployeeAndSsnContext>(null);
            // If you want to see the TSQL generated by EF, uncomment this
            //this.Database.Log = msg => Console.WriteLine(msg);
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // The existing table name does not end with 's'
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }
        public DbSet<EmployeeIdAndSsn>? EmployeeIdAndSsn { get; set; }
    }
}
